vich_uploader:
  db_driver: orm
  metadata:
    type: attribute
  mappings:
    media:
      uri_prefix: '%app.path.media%'
      upload_destination: '%kernel.project_dir%/public%app.path.media%'
      namer: Vich\UploaderBundle\Naming\OrignameNamer
#      inject_on_load: false
      inject_on_load: true
      delete_on_update: true
      delete_on_remove: true